// <auto-generated />
namespace ContestantSystem.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedTestpropertyon_ContestantRating_AverageRatting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedTestpropertyon_ContestantRating_AverageRatting));
        
        string IMigrationMetadata.Id
        {
            get { return "201911281142222_AddedTestpropertyon_ContestantRating_AverageRatting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
